NoMessage

diff --git a/git-parallel-updates b/git-parallel-updates
--- a/git-parallel-updates
+++ b/git-parallel-updates
@@ -1,52 +1,38 @@
 #!/bin/bash
 # Author: Gokberk Cinbis, May 2020
 
-# TODO pause & exit options
-
 set -e
-FOO=${TMUX_PARALLEL_EXEC_MAX_PANES_PER_WINDOW:=9}
+ 
+# TODO in progress
 
-function __uniqueid__()
-{
-    # date, time, process info
-    local d=`command date +%Y%m%d`
-    local t=`command date +%H-%M-%S` # hour.minute.seconds (dots are useful for time, otherwise very unreadible)
-    #local host=`hostname`
-    local pid="$$"
-    echo tmux-parallel-exec-at-dirs_${d}_${t}_${pid}
+function __git_parallel_updates__() {
+    gitsyncroot
+    status=$?
+    if [ $status -eq 0 ]; then
+        exit
+    fi
 }
 
-function __tmux__parallel_exec_at_dirs__()
+function __git_parallel_updates__()
 {
     local narg=$#
-    local session_name=`__uniqueid__`
 
-    if [ $narg -lt 2 ]
+    if [ $narg -ne 2 ]
     then
-        echo "tmux-parallel-exec-at-dirs <cmd> <dir1> ... <dirN>"
+        echo "git-parallel-updates <cmd> <all_git_root>"
         echo ""
-        echo "Run a single command within multiple directories via tmux panes & windows."
-        echo "Creates a new window every TMUX_PARALLEL_EXEC_MAX_PANES_PER_WINDOW (default 9) panes to avoid too small panes."
+        echo "Recursively find all git repositories located under all_git_root"
+        echo "Run <cmd> within these directories via tmux-parallel-exec-at-dirs."
+        echo "Automatically close panes with no errors."
         echo ""
         echo "EXAMPLES"
-        echo '* tmux-parallel-exec-at-dirs pwd ~/*'
-        echo '* tmux-parallel-exec-at-dirs 'git pull' ~/projects/repo1 ~/projects/repo2'
-        echo '* tmux-parallel-exec-at-dirs 'git pull' ~/projects/*'
-        echo ''
-        echo 'EXAMPLE: SYNC MULTIPLE GIT REPOS AND CLOSE PANES WITH NO ERRORS'
-        echo ''
-        echo '  function gitsyncrootandexit() {'
-        echo '      gitsyncroot'
-        echo '      status=$?'
-        echo '      if [ $status -eq 0 ]; then'
-        echo '          exit'
-        echo '      fi'
-        echo '  }'
-        echo '  mygitdirs=$(find ~/projects -type d -name ".git" -exec dirname {} \; | xargs echo)'
-        echo '  alias projsync="tmux-parallel-exec-at-dirs gitsyncrootandexit $mygitdirs"'
-        echo ""
-        echo "SEE tmux-parallel-exec tmux-parallel-exec-at-dirs"
+        echo "* git-parallel-updates 'git pull' ~/projects"
+        echo "* git-parallel-updates 'gitsyncroot' ~/projects"
         exit 1
+    fi
+
+    if [[ cmd=='__git_parallel_updates_wrapper__ ]]; then
+
     fi
    
     local cmd="$1"
