Improved exit code and modified repository handling

diff --git a/git_checkhash b/git_checkhash
--- a/git_checkhash
+++ b/git_checkhash
@@ -7,14 +7,22 @@ if [ "$#" -eq 1 ]; then
 else
     echo 'git_checkhash <file>'
     echo ''   
-    echo 'Check whether the current git hash to make sure the right code-base is being used for evaluating a pre-trained model'
+    echo 'Check the current git hash to make sure the right code-base is being used for evaluating a pre-trained model'
+    echo 'Test fails if there are uncommitted changes or the current commit hash differs from the one in <file>.'
     echo ''
     echo 'EXIT CODES'
     echo '  0 if check passes'
-    echo '  non-zero otherwise'
-    echo
+    echo '  non-zero otherwise, with following details:'
+    echo '      1 if <file> does not exist'
+    echo '      2 if there are uncommitted changes'
+    echo '      3 if working copy corresponds to a different commit'
+    echo '      4 if the number of input args is invalid'
+    echo '      some non-zero if git_writehash reports another error'
+    echo ''
+    echo 'Important: for some errors, there may not be any error message printed on screen'
+    echo ''
     echo 'Suggested use of the exit code:'
-    echo '  if git_checkhash <file>; then echo "git_checkhash passed"; else exit 1; fi'
+    echo '  if git_checkhash <file>; then echo "git_checkhash passed"; else exit $?; fi'
     echo ''   
     echo 'SUGGESTED USE'   
     echo 'Call git_uniqueid to generate a log directory in the beginning of an experiment script'   
@@ -25,17 +33,23 @@ else
     echo 'git_uniqueid    Generate a unique log file/directory name for running an experiment'
     echo 'git_writehash   Write git hash into a file'
     echo 'git_checkhash   Check whether the current git hash to make sure the right code-base is being used for evaluating a pre-trained model'
-    exit 3
+    exit 4
 fi
 
 if [ ! -f $file ]
 then
     echo "git_checkhash: $file does not exit."
+    exit 1
+fi
+idf=$(command cat $file)
+
+# handle this explicitly to report the problem:
+if [[ ! -z $(command git status -s) ]]; then # see https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes
+    echo "git_checkhash: there are uncommitted changes. Checkout version ${idf} to use the right version."
     exit 2
 fi
 
-idf=$(command cat $file)
-idg=$(command git_writehash | head -1)
+idg=$(command git_writehash) # exits automatically if git_writehash returns a non-zero exit code.
 
 # trim
 idf=$(echo -e "${idf}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
@@ -43,11 +57,12 @@ idg=$(echo -e "${idg}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
 
 if [ "${idf}" == "${idg}" ]
 then
+    echo "git_checkhash: OK."
     exit 0
 else
     echo "git_checkhash: hash differs. Checkout version ${idf} to use the right version."
     # RUN: "git checkout ${idf}"
-    exit 1
+    exit 3
 fi
 
 
diff --git a/git_uniqueid b/git_uniqueid
--- a/git_uniqueid
+++ b/git_uniqueid
@@ -1,6 +1,7 @@
 #!/bin/bash
 # Author: Gokberk Cinbis, 2017
 set -e
+#set -o pipefail -e # maybe this instead?
 
 function helpandpanic()
 {
@@ -30,7 +31,7 @@ function helpandpanic()
     echo
     echo 'Suggested use of the exit code:'
     echo '  if id=$(git_uniqueid); then'
-    echo '      echo run experiment with log directory $id'
+    echo '      echo run experiment with log id $id'
     echo '  else'
     echo '      echo "there are uncommitted changes or not a git directory"'
     echo '  fi'
@@ -66,12 +67,16 @@ if git rev-parse --git-dir > /dev/null 2>&1; then
     # 'index: commit index relative to the first one, a hacky commit index'
     # commitindex=`git rev-list --full-history --all --abbrev-commit | wc -l | sed -e 's/^ *//'` # commit index
 
+    set +e # forgive errors below
     h=`git_writehash` # hash
+    writehash_exit=$?
+    set -e # exit on error
+
     branch=`git rev-parse --abbrev-ref HEAD`
     if [[ -z $(git status -s) ]]; then # see https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes
-        rc=0 # return code
+        rc=$writehash_exit # return code is zero unless git_writehash has reported an error
     else
-        h=${h}_modified
+        # git_writehash does this: h=${h}_modified
         rc=1 # return code
     fi
     # ih="${commitindex}_${h}"
diff --git a/git_writehash b/git_writehash
--- a/git_writehash
+++ b/git_writehash
@@ -2,27 +2,20 @@
 # Author: Gokberk Cinbis, 2017
 set -e
 
-# NO! cmd='command git rev-list --full-history --all | head -1' 
-# If we've checkout an old revision (ie. in detached-HEAD state), this returns an incorrect result.
-cmd='git rev-parse --verify HEAD'
-
-if [ "$#" -eq 0 ]; then
-    file="$1"
-    ${cmd}
-elif [ "$#" -eq 1 ]; then
-    file="$1"
-    if [ -f "$file" ]
-    then
-        echo "git_writehash: "$file" already exists. First delete existing output file."
-        exit 1
-    fi
-    ${cmd} > "$file"
-else
+function helpandpanic()
+{
     echo 'git_writehash <file>'
     echo 'Echo git hash'
     echo ''   
     echo 'git_writehash <file>'
-    echo 'Write git hash into a file. Exists if file already exists.'
+    echo 'Write git hash into a file. Exists if file already exists. Writes <hash>_modified if there are uncommitted changes '
+    echo ''   
+    echo 'EXIT CODES'
+    echo '  0 normally'
+    echo '  1 if there are uncommited changes'
+    echo '  2 if <file> already exists'
+    echo '  3 if the number of input args is invalid'
+    echo '  other if a subprocess fails (eg, not a git repository)'
     echo ''   
     echo 'SUGGESTED USE'   
     echo 'Call git_uniqueid to generate a log directory in the beginning of an experiment script'   
@@ -34,6 +27,34 @@ else
     echo 'git_writehash   Write git hash into a file'
     echo 'git_checkhash   Check whether the current git hash to make sure the right code-base is being used for evaluating a pre-trained model'
     exit 3
+}
+
+# NO! cmd='command git rev-list --full-history --all | head -1' 
+# If we've checkout an old revision (ie. in detached-HEAD state), this returns an incorrect result.
+h=$(command git rev-parse --verify HEAD)
+# not a git repository: git_writehash returns 128.
+
+if [[ -z $(command git status -s) ]]; then # see https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes
+    rc=0 # return code
+else
+    h=${h}_modified
+    rc=1 # return code
+fi
+
+if [ "$#" -eq 0 ]; then
+    echo $h 
+    exit $rc
+elif [ "$#" -eq 1 ]; then
+    file="$1"
+    if [ -f "$file" ]
+    then
+        echo "git_writehash: "$file" already exists. First delete existing output file."
+        exit 1
+    fi
+    echo $h > "$file"
+    exit $rc
+else
+    helpandpanic
 fi
 
 
